[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"
  # Force rebuild - 2024-04-01-13-20

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
